# Generated by Django 4.2.3 on 2023-07-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_propietario_remove_departamento_nombrepropietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='edificios.propietario'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
